"""Smoke test for TopicPilot-CN Phase 01 — runs against a live uvicorn.

Usage:
    python scripts/smoke.py [BASE_URL]

Default BASE_URL = http://127.0.0.1:18181.

Reads payloads from tmp/smoke_placeholder.json and tmp/smoke_complete.json
(generated by scripts/make_smoke_payloads.py). Runs all four endpoints,
asserts status codes, and prints a summary.

Exits with non-zero on any failure.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import httpx

# Force UTF-8 stdout so Chinese characters survive Windows console codecs.
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

REPO = Path(__file__).resolve().parents[1]
TMP = REPO / "tmp"
BASE = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:18181"


def _check(label: str, ok: bool, detail: str = "") -> bool:
    mark = "OK " if ok else "FAIL"
    print(f"  [{mark}] {label}{(' — ' + detail) if detail else ''}")
    return ok


def _scrub(c: httpx.Client) -> None:
    """Delete any leftover smoke projects from previous runs (best-effort)."""

    for case_id in ("SMOKE_TBD_AI", "SMOKE_FULL_AI"):
        try:
            c.delete(f"/api/v1/projects/by-case/{case_id}")
        except Exception:
            pass


def main() -> int:
    print(f"=== smoke @ {BASE} ===")

    # Generate fresh payloads each run with a unique suffix so re-runs don't 409
    # before they can validate the placeholder path.
    import time
    suffix = str(int(time.time() * 1000))[-6:]

    placeholder_body = json.loads((TMP / "smoke_placeholder.json").read_text(encoding="utf-8"))
    placeholder_body["intake"]["case_id"] = f"SMOKE_TBD_{suffix}"

    complete_body = json.loads((TMP / "smoke_complete.json").read_text(encoding="utf-8"))
    complete_body["intake"]["case_id"] = f"SMOKE_FULL_{suffix}"

    failures = 0
    with httpx.Client(base_url=BASE, timeout=10.0) as c:
        _scrub(c)
        # 1) /health
        r = c.get("/health")
        if not _check("GET /health", r.status_code == 200 and r.json().get("phase") == "01",
                      f"HTTP {r.status_code} {r.text[:80]}"):
            failures += 1

        # 2) POST placeholder (expects 201 + rating D)
        r = c.post("/api/v1/projects", json=placeholder_body)
        ok = r.status_code == 201 and r.json()["payload"]["intake_rating"] == "D"
        if not _check("POST placeholder → rating=D",
                      ok, f"HTTP {r.status_code} {r.text[:120]}"):
            failures += 1
            return failures  # need the id for next steps
        placeholder_id = r.json()["id"]
        print(f"    → placeholder id={placeholder_id}")

        # 3) GET placeholder
        r = c.get(f"/api/v1/projects/{placeholder_id}")
        if not _check("GET placeholder", r.status_code == 200 and r.json()["id"] == placeholder_id,
                      f"HTTP {r.status_code}"):
            failures += 1

        # 4) POST validate (placeholder) → expect BLOCKED + D
        r = c.post(f"/api/v1/projects/{placeholder_id}/intake/validate")
        data = r.json()
        ok = (
            r.status_code == 200
            and data["outcome"] == "BLOCKED"
            and data["intake_rating"] == "D"
            and data["allow_proceed_to_phase02"] is False
        )
        if not _check("validate placeholder → BLOCKED/D", ok,
                      f"HTTP {r.status_code} outcome={data.get('outcome')} rating={data.get('intake_rating')}"):
            failures += 1

        # 5) POST complete (expects 201 + rating A)
        r = c.post("/api/v1/projects", json=complete_body)
        ok = r.status_code == 201 and r.json()["payload"]["intake_rating"] == "A"
        if not _check("POST complete → rating=A",
                      ok, f"HTTP {r.status_code} {r.text[:120]}"):
            failures += 1
            return failures
        complete_id = r.json()["id"]
        print(f"    → complete id={complete_id}")

        # 6) GET complete
        r = c.get(f"/api/v1/projects/{complete_id}")
        if not _check("GET complete", r.status_code == 200 and r.json()["id"] == complete_id,
                      f"HTTP {r.status_code}"):
            failures += 1

        # 7) validate complete → expect OK + A
        r = c.post(f"/api/v1/projects/{complete_id}/intake/validate")
        data = r.json()
        ok = (
            r.status_code == 200
            and data["outcome"] == "OK"
            and data["intake_rating"] == "A"
            and data["allow_proceed_to_phase02"] is True
        )
        if not _check("validate complete → OK/A", ok,
                      f"HTTP {r.status_code} outcome={data.get('outcome')}"):
            failures += 1

        # 8) duplicate case_id → 409
        r = c.post("/api/v1/projects", json=complete_body)
        if not _check("duplicate case_id → 409", r.status_code == 409,
                      f"HTTP {r.status_code}"):
            failures += 1

        # 9) missing project → 404
        r = c.get("/api/v1/projects/99999")
        if not _check("missing project → 404", r.status_code == 404,
                      f"HTTP {r.status_code}"):
            failures += 1

        # 10) D→A clarification loop: hit the placeholder project again
        r = c.post(f"/api/v1/projects/{placeholder_id}/intake/validate")
        data = r.json()
        ok = (
            r.status_code == 200
            and data["intake_rating"] == "D"
            and data["outcome"] == "BLOCKED"
        )
        if not _check("validate placeholder still BLOCKED (loop confirm)", ok,
                      f"HTTP {r.status_code} outcome={data.get('outcome')}"):
            failures += 1

    print()
    if failures:
        print(f"=== SMOKE FAILED ({failures} failures) ===")
        return 1
    print("=== SMOKE OK ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
